### ISSUE TITLE
Sigue el problema de la UI

### ISSUE THREAD

**Issue by NatryN** [bathtimethiago/Spotify11#1]
![image](https://user-images.githubusercontent.com/100478504/166080876-06a66597-43c1-4a31-a2ac-4824c71463ad.png)
El error es el mismo que la versión original.

**Comment by bathtimethiago** [comment]
https://spotify.br.uptodown.com/windows/download/4431137
Instale esta versión, en el futuro haré un tutorial para bloquear las actualizaciones de Spotify porque la última versión no es compatible con el tema.
